import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
    "./src/pages/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#d2c5ab",
        error: "#ffb4ab",
        "surface-dim": "#10141a",
        "on-secondary-fixed": "#161c23",
        "text-muted": "#8B949E",
        "surface-container-low": "#181c22",
        "secondary-fixed": "#dde3ec",
        "on-primary-container": "#6e5400",
        "brand-yellow-hover": "#E0A800",
        "on-tertiary-fixed": "#001f24",
        background: "#10141a",
        "status-error": "#F85149",
        "text-high-contrast": "#F0F6FC",
        "inverse-primary": "#765a00",
        secondary: "#c1c7d0",
        "on-secondary-fixed-variant": "#41474f",
        "on-tertiary-container": "#00616d",
        "primary-fixed": "#ffdf95",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#31353c",
        "on-secondary-container": "#b0b5be",
        surface: "#10141a",
        "on-tertiary-fixed-variant": "#004f58",
        "surface-bright": "#353940",
        "on-background": "#dfe2eb",
        "tertiary-fixed-dim": "#00daf3",
        outline: "#9b8f78",
        "surface-track": "#21262D",
        "on-tertiary": "#00363d",
        "inverse-surface": "#dfe2eb",
        "secondary-fixed-dim": "#c1c7d0",
        "on-surface": "#dfe2eb",
        "inverse-on-surface": "#2d3137",
        "on-error": "#690005",
        "error-container": "#93000a",
        "surface-base": "#0D1117",
        "primary-container": "#ffc709",
        primary: "#ffe9b9",
        "surface-card": "#161B22",
        "primary-fixed-dim": "#f5bf00",
        "tertiary-container": "#00e3fd",
        "on-primary-fixed-variant": "#594400",
        "secondary-container": "#41474f",
        "border-subtle": "#30363D",
        "on-primary": "#3e2e00",
        tertiary: "#bdf4ff",
        "on-primary-fixed": "#251a00",
        "surface-container-high": "#262a31",
        "tertiary-fixed": "#9cefff",
        "outline-variant": "#4f4632",
        "on-secondary": "#2b3138",
        "surface-container-lowest": "#0a0e14",
        "surface-variant": "#31353c",
        "surface-tint": "#f5bf00",
        "surface-container": "#1c2026",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xl": "2rem",
        "space-md": "1rem",
        "gutter-desktop": "1.5rem",
        "space-2xl": "3rem",
        "margin-desktop": "2rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        margin: "1rem",
        gutter: "1rem",
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-lg": [
          "28px",
          { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": [
          "20px",
          { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "30px", letterSpacing: "-0.015em", fontWeight: "700" },
        ],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
